site:
  title: Nuvolaris Community
  url: https://nuvolaris.github.io
  start_page: nuvolaris::index.adoc
  keys:
    google_analytics: 'G-0WXXCQMZB6'

content:
  sources:
    - url: https://github.com/nuvolaris/nuvolaris-documentation
      branches: 3.0.0
    - url: https://github.com/nuvolaris/nuvolaris-documentation
      branches: 0.2.2

ui: 
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  output_dir: assets
  supplemental_files: ./supplemental-ui

output:
  clean: true
  dir: ./docs
